# database configs
dbDriverName: "jdbc:sqlite:ebaytools.db"
mainTableName: "sale_items"

# miscellaneous
logoImageFilename: "logo_200x200.png"

# clauses to build out ebay shopping api calls
#
# here is a sample REST URI that will be built out
#  https://open.api.ebay.com/shopping?
#  callname=GetSingleItem&
#  responseencoding=XML&
#  appid=YourAppIDHere&
#  siteid=0&
#  version=967&
#  ItemID=180126682091

# api OAuth2 token retrieval info
accessTokenEndpoint: "https://api.ebay.com/identity/v1/oauth2/token"
authorizationBaseUrl: "https://auth.ebay.com/oauth2/authorize"
defaultScope: "https://api.ebay.com/oauth/api_scope"

baseApiUri: "https://open.api.ebay.com/shopping"
# append one of the following to baseApi
getItemCallname: "callname=GetSingleItem"
getItemStatusCallname: "callname=GetItemStatus"
getShippingCostsCallName: "callname=GetShippingCosts"

rsEncoding: "responseencoding=JSON"
# todo: is there a generic yet secure appID for any user
appid: DominicA-eShopToo-PRD-8c8ee5576-77674917
certid: PRD-c8ee55764391-a5d8-4069-9a1f-f8f9
devid: 0a0fe5d9-047c-4aaf-b29b-c00fe3a931e8
redirecturi: Dominic_Ancheta-DominicA-eShopT-proczkyrc
siteid: "siteid=0"
apiVersion: "version=1199"

#todo: determine solution to include which selector to use based on the app call needs
# maybe only a few combinations of each are needed to get the data needed
includeDetailsSelector: "IncludeSelector=Description,Details"

#append any of these to previous details selector (let's make this default) with a comma
includeShippingSelector: "ShippingCosts"
includeDescriptionSelector: "TextDescription"
